name: Deploy

on:
  push:
    branches:
      - main  # Modifique para o branch que deseja usar para o deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Modifique para a versão do Node.js usada no seu projeto

      - name: Install dependencies
        run: |
          cd aula10
          npm install

      - name: Build project
        run: |
          cd aula10
          npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./aula10/dist  # Caminho correto para a pasta de build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Modifique conforme o branch desejado

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./aula10/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Certifique-se que a versão é a mais recente
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Use 'personal_token' em vez de 'github_token'
          publish_dir: ./aula10/dist
